# Libraries

In [1]:
import os
import requests
import pandas as pd, json, ast
import requests
import json
from datetime import datetime, timedelta
import time
import ast

import paho.mqtt.client as mqtt

# 1. DATA RETRIEVAL

## 1.1. Declaring Constants

In [ ]:
# ADD API KEY HERE
API_KEY="" # API Key add here

In [3]:
#Configs
BASE_URL = "https://api.openelectricity.org.au/v4"
HEADERS = {"Authorization": f"Bearer {API_KEY}"}
OUTPUT_DIR = "./output"
os.makedirs(OUTPUT_DIR, exist_ok=True)
INTERVAL = "5m"

# Date range for 1st week of October 2025, End date is not inclusive.
START_DATE = datetime(2025, 10, 1)
END_DATE = datetime(2025, 10, 8)
REQUEST_DELAY = 0  # seconds between requests to avoid API limits

## 1.2. Fetching the list of Facilities

Fetch the list of all facilities for a given electricity network (default=NEM),  
Returns: pd.DataFrame: Facility metadata including name, region, code, location, and units.

In [4]:
def fetch_all_facilities(network: str = "NEM") -> pd.DataFrame:
    
    url = f"{BASE_URL}/facilities/"
    params = {
        "network_code": "NEM",
    }

    print("IN PROGRESS Fetching all facilities...")
    r = requests.get(url, headers=HEADERS, params=params)
    if r.status_code >= 400:
        print("API Error:")
        try:
            print(r.json())
        except Exception:
            print(r.text)
        r.raise_for_status()

    data = r.json().get("data", [])
    rows = []
    for entry in data:
        rows.append({
            "name": entry.get("name"),
      "network_id": entry.get("network_id"),
      "network_region": entry.get("network_region"),
      "description": entry.get("description"),
      "location": entry.get("location"),
       "code": entry.get("code"),

            "units": entry.get("units"),
        
          "created_at": entry.get("created_at"),
          "updated_at": entry.get("updated_at"),
       
       
        })

    df = pd.DataFrame(rows)
    print(f"SUCCESS Retrieved {len(df)} facilities")
    return df

facilities_df = fetch_all_facilities()

IN PROGRESS Fetching all facilities...
SUCCESS Retrieved 625 facilities

### 1.2.1. PER-FACILITY POWER GENERATED (5 min interval)

fetches 5-minute interval power generation data for every facility in the NEM network.

In [5]:
#fetches 5-minute interval power generation data for every facility in the NEM network.  
def fetch_facility_power(facility_id: str, start: datetime, end: datetime) -> pd.DataFrame:
    """Fetch 5-minute power data for a single facility and flatten it."""
    url = f"{BASE_URL}/data/facilities/NEM"
    #setting request parameters 
    params = {
        "metrics": ["power"],
        "interval": INTERVAL,
        "facility_code": facility_id,
        "date_start": START_DATE,
        "date_end": END_DATE,
        
    }

    # Make request and handle API / network issues safely
    try:
        r = requests.get(url, headers=HEADERS, params=params)
        r.raise_for_status()
        json_data = r.json()
    except Exception as e:
        print(f" Failed to fetch power for {facility_id}: {e}")
        return pd.DataFrame()

    # Check if the API returned success
    if not json_data.get("success", False):
        print(f" API returned failure for {facility_id}: {json_data.get('error')}")
        return pd.DataFrame()

    data = json_data.get("data", [])
    rows = []

    # Flatten nested JSON:
    for entry in data:
        unit_code = entry.get("unit", "MW")
        for res in entry.get("results", []):
            for point in res.get("data", []):
                timestamp, value = point
                rows.append({
                    "facility_id": facility_id,
                    "unit_code": unit_code,
                    "timestamp": timestamp,
                    "power_MW": value
                })

    return pd.DataFrame(rows)



# Step 1: Load facilities CSV (if needed)
facility_ids = facilities_df["code"]
print(f"IN PROGRESS Fetching power for {len(facility_ids)} facilities...")

all_power = []
count =1
# Step 2: Iterate over facilities
for facility_id in facility_ids:
    print(f"Fetching power for facility {facility_id}...count no "+ str(count))
    count+=1
    power_df = fetch_facility_power(facility_id, START_DATE, END_DATE)
    if power_df.empty:
        print(f" No data for {facility_id}")
    all_power.append(power_df)
    time.sleep(REQUEST_DELAY)

# Step 3: Combine all facilities
power_df_raw = pd.concat(all_power, ignore_index=True)

IN PROGRESS Fetching power for 625 facilities...
Fetching power for facility ADP...count no 1
Fetching power for facility ALBANY...count no 2
 Failed to fetch power for ALBANY: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=ALBANY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for ALBANY
Fetching power for facility ALDGASF...count no 3
Fetching power for facility AMCORGR...count no 4
 Failed to fetch power for AMCORGR: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=AMCORGR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for AMCORGR
Fetching power for facility ANGASTON...count no 5
Fetching power for facility APS...count no 6
 Failed to fetch power for APS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=APS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for APS
Fetching power for facility APPIN...count no 7
 Failed to fetch power for APPIN: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=APPIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for APPIN
Fetching power for facility ARWF...count no 8
Fetching power for facility AVLSF...count no 9
Fetching power for facility AWABAREF...count no 10
 Failed to fetch power for AWABAREF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=AWABAREF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for AWABAREF
Fetching power for facility BADGINGARRA...count no 11
 Failed to fetch power for BADGINGARRA: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BADGINGARRA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BADGINGARRA
Fetching power for facility DEIBDL...count no 12
Fetching power for facility BAKING...count no 13
 Failed to fetch power for BAKING: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BAKING&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BAKING
Fetching power for facility BHWF...count no 14
Fetching power for facility BALBESS...count no 15
Fetching power for facility BBASEHOS...count no 16
 Failed to fetch power for BBASEHOS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BBASEHOS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BBASEHOS
Fetching power for facility BANGOWF...count no 17
Fetching power for facility BAPS...count no 18
 Failed to fetch power for BAPS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BAPS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BAPS
Fetching power for facility BANKSPT...count no 19
 Failed to fetch power for BANKSPT: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BANKSPT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BANKSPT
Fetching power for facility BANNSP...count no 20
Fetching power for facility BARCALDN...count no 21
Fetching power for facility BARCSF...count no 22
Fetching power for facility BARKIPS...count no 23
Fetching power for facility BARRON...count no 24
Fetching power for facility BASTYAN...count no 25
Fetching power for facility BAYSW...count no 26
Fetching power for facility BBDISEL1...count no 27
 Failed to fetch power for BBDISEL1: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BBDISEL1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BBDISEL1
Fetching power for facility BELLBAY...count no 28
 Failed to fetch power for BELLBAY: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BELLBAY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BELLBAY
Fetching power for facility BBP31...count no 29
Fetching power for facility BHBBESS...count no 30
 Failed to fetch power for BHBBESS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BHBBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BHBBESS
Fetching power for facility BCBESS...count no 31
 Failed to fetch power for BCBESS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BCBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BCBESS
Fetching power for facility BLAIRFOX_BEROSRD_WF...count no 32
 Failed to fetch power for BLAIRFOX_BEROSRD_WF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLAIRFOX_BEROSRD_WF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BLAIRFOX_BEROSRD_WF
Fetching power for facility BRYB1WF1...count no 33
Fetching power for facility BERWICK...count no 34
 Failed to fetch power for BERWICK: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BERWICK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BERWICK
Fetching power for facility BERYLSF...count no 35
Fetching power for facility BIALAWF...count no 36
Fetching power for facility BLAYNEY...count no 37
 Failed to fetch power for BLAYNEY: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLAYNEY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BLAYNEY
Fetching power for facility BLINDCREEK...count no 38
 Failed to fetch power for BLINDCREEK: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLINDCREEK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BLINDCREEK
Fetching power for facility SNOWY6...count no 39
Fetching power for facility BLUEGSF...count no 40
Fetching power for facility BLULAKE...count no 41
 Failed to fetch power for BLULAKE: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLULAKE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BLULAKE
Fetching power for facility BLUEWATERS...count no 42
 Failed to fetch power for BLUEWATERS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLUEWATERS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BLUEWATERS
Fetching power for facility BLYTHB...count no 43
Fetching power for facility BOCOROCK...count no 44
Fetching power for facility BODWF...count no 45
Fetching power for facility BOGGABRI...count no 46
 Failed to fetch power for BOGGABRI: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BOGGABRI&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BOGGABRI
Fetching power for facility MCKAY...count no 47
Fetching power for facility BOLIVAR...count no 48
Fetching power for facility BOLIVPS...count no 49
Fetching power for facility BOMENSF...count no 50
Fetching power for facility BCWF...count no 51
 Failed to fetch power for BCWF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BCWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BCWF
Fetching power for facility BBATTERY...count no 52
Fetching power for facility BRAEMARA...count no 53
Fetching power for facility B2PS...count no 54
Fetching power for facility BREMER_BAY...count no 55
 Failed to fetch power for BREMER_BAY: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BREMER_BAY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BREMER_BAY
Fetching power for facility BRNDBES...count no 56
Fetching power for facility BROADMDW...count no 57
 Failed to fetch power for BROADMDW: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BROADMDW&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BROADMDW
Fetching power for facility BRDD...count no 58
 Failed to fetch power for BRDD: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BRDD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BRDD
Fetching power for facility BWTR1...count no 59
Fetching power for facility BHILLGT...count no 60
Fetching power for facility BROKENH...count no 61
Fetching power for facility BHB...count no 62
Fetching power for facility BROOKLYN...count no 63
 Failed to fetch power for BROOKLYN: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BROOKLYN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BROOKLYN
Fetching power for facility BROWNMT...count no 64
 Failed to fetch power for BROWNMT: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BROWNMT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BROWNMT
Fetching power for facility BPLANDF...count no 65
 Failed to fetch power for BPLANDF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BPLANDF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BPLANDF
Fetching power for facility WELLINGTONBESS...count no 66
 Failed to fetch power for WELLINGTONBESS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WELLINGTONBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for WELLINGTONBESS
Fetching power for facility BULGANA...count no 67
Fetching power for facility BUSF...count no 68
 Failed to fetch power for BUSF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BUSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BUSF
Fetching power for facility BNGSF1...count no 69
Fetching power for facility BNGSF2...count no 70
Fetching power for facility BUNGAMB...count no 71
 Failed to fetch power for BUNGAMB: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BUNGAMB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BUNGAMB
Fetching power for facility BDONGHYD...count no 72
 Failed to fetch power for BDONGHYD: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BDONGHYD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BDONGHYD
Fetching power for facility BURRIN...count no 73
 Failed to fetch power for BURRIN: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BURRIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BURRIN
Fetching power for facility BUTLERSG...count no 74
Fetching power for facility CALBESS1...count no 75
 Failed to fetch power for CALBESS1: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CALBESS1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CALBESS1
Fetching power for facility CALBESS2...count no 76
 Failed to fetch power for CALBESS2: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CALBESS2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CALBESS2
Fetching power for facility CALL_A...count no 77
 Failed to fetch power for CALL_A: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CALL_A&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CALL_A
Fetching power for facility CALL_B...count no 78
Fetching power for facility CALLIDEC1...count no 79
Fetching power for facility CANUNDA1...count no 80
Fetching power for facility CAPBES...count no 81
Fetching power for facility CAPTL_WF...count no 82
Fetching power for facility CESF...count no 83
 Failed to fetch power for CESF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CESF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CESF
Fetching power for facility CARAG...count no 84
 Failed to fetch power for CARAG: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CARAG&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CARAG
Fetching power for facility CHWF1...count no 85
 Failed to fetch power for CHWF1: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CHWF1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CHWF1
Fetching power for facility CRWARP...count no 86
 Failed to fetch power for CRWARP: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CRWARP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CRWARP
Fetching power for facility LI_WY_CA...count no 87
Fetching power for facility CATHROCK...count no 88
Fetching power for facility CTHLWF...count no 89
Fetching power for facility CETHANA...count no 90
Fetching power for facility CHALLWF...count no 91
Fetching power for facility CHPSTWF...count no 92
 Failed to fetch power for CHPSTWF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CHPSTWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CHPSTWF
Fetching power for facility CHYTWF...count no 93
Fetching power for facility CHILDSF...count no 94
Fetching power for facility CHBESS...count no 95
Fetching power for facility CBWWBA...count no 96
Fetching power for facility CLARESF...count no 97
Fetching power for facility CLRKCWF...count no 98
Fetching power for facility CLAYTON...count no 99
 Failed to fetch power for CLAYTON: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CLAYTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CLAYTON
Fetching power for facility CLEMGPWF...count no 100
Fetching power for facility CLERMSF...count no 101
Fetching power for facility CLOVER...count no 102
Fetching power for facility CLUNY...count no 103
Fetching power for facility COCKBURN...count no 104
 Failed to fetch power for COCKBURN: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COCKBURN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COCKBURN
Fetching power for facility CODRGTON...count no 105
 Failed to fetch power for CODRGTON: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CODRGTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CODRGTON
Fetching power for facility COHUNSF1...count no 106
Fetching power for facility COLEASF...count no 107
Fetching power for facility COLWF01...count no 108
Fetching power for facility INVESTEC_COLLGAR...count no 109
 Failed to fetch power for INVESTEC_COLLGAR: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=INVESTEC_COLLGAR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for INVESTEC_COLLGAR
Fetching power for facility COLLIE...count no 110
 Failed to fetch power for COLLIE: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLLIE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COLLIE
Fetching power for facility COLLIE_ESR4...count no 111
 Failed to fetch power for COLLIE_ESR4: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLLIE_ESR4&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COLLIE_ESR4
Fetching power for facility COLLIE_ESR...count no 112
 Failed to fetch power for COLLIE_ESR: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLLIE_ESR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COLLIE_ESR
Fetching power for facility COLLIE_BESS2...count no 113
 Failed to fetch power for COLLIE_BESS2: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLLIE_BESS2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COLLIE_BESS2
Fetching power for facility COLLIE_ESR5...count no 114
 Failed to fetch power for COLLIE_ESR5: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLLIE_ESR5&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COLLIE_ESR5
Fetching power for facility COLNSV...count no 115
 Failed to fetch power for COLNSV: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLNSV&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COLNSV
Fetching power for facility CSPVPS...count no 116
Fetching power for facility COLONGRA...count no 117
Fetching power for facility COLUMSF...count no 118
Fetching power for facility CPSA...count no 119
Fetching power for facility CONDONG1...count no 120
Fetching power for facility CBWF...count no 121

### 1.2.2. PER-FACILITY CO2 EMISSIONS (5 min interval)

fetches 5-minute interval emnission data for every facility in the NEM network.

In [6]:
#Fetches 5-minute emissions data for a single facility and returns a flattened DataFrame.
def fetch_facility_emissions(facility_id: str, start: datetime, end: datetime) -> pd.DataFrame:
    """Fetch 5-minute emissions data for a single facility and flatten it."""
    url = f"{BASE_URL}/data/facilities/NEM"
    # Passing Parameters
    params = {
        "metrics": ["emissions"],
        "interval": INTERVAL,
        "facility_code": facility_id,
        "date_start": START_DATE,
        "date_end": END_DATE,
    }

    # Make request and safely handle connection / API issues
    try:
        r = requests.get(url, headers=HEADERS, params=params)
        r.raise_for_status()
        json_data = r.json()
    except Exception as e:
        print(f" Failed to fetch emissions for {facility_id}: {e}")
        return pd.DataFrame()

    # Check API success flag
    if not json_data.get("success", False):
        print(f" API returned failure for {facility_id}: {json_data.get('error')}")
        return pd.DataFrame()

    data = json_data.get("data", [])
    rows = []

    # Flatten nested structure
    for entry in data:
        unit_code = entry.get("unit", "tCO2e")  # adjusted unit label
        for res in entry.get("results", []):
            for point in res.get("data", []):
                timestamp, value = point
                rows.append({
                    "facility_id": facility_id,
                    "unit_code": unit_code,
                    "timestamp": timestamp,
                    "emission": value
                })

    return pd.DataFrame(rows)


print(f"IN PROGRESS Fetching emissions for {len(facility_ids)} facilities...")

all_emissions = []

# Step 2: Iterate over facilities
count = 1
for facility_id in facility_ids:
    print(f"Fetching emissions for facility {facility_id}... count no {count}")
    count += 1
    emissions_df = fetch_facility_emissions(facility_id, START_DATE, END_DATE)
    if emissions_df.empty:
        print(f" No data for {facility_id}")
    all_emissions.append(emissions_df)
    time.sleep(REQUEST_DELAY)

# Step 3: Combine all facilities
emissions_df_raw = pd.concat(all_emissions, ignore_index=True)

IN PROGRESS Fetching emissions for 625 facilities...
Fetching emissions for facility ADP... count no 1
Fetching emissions for facility ALBANY... count no 2
 Failed to fetch emissions for ALBANY: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=ALBANY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for ALBANY
Fetching emissions for facility ALDGASF... count no 3
Fetching emissions for facility AMCORGR... count no 4
 Failed to fetch emissions for AMCORGR: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=AMCORGR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for AMCORGR
Fetching emissions for facility ANGASTON... count no 5
Fetching emissions for facility APS... count no 6
 Failed to fetch emissions for APS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=APS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for APS
Fetching emissions for facility APPIN... count no 7
 Failed to fetch emissions for APPIN: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=APPIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for APPIN
Fetching emissions for facility ARWF... count no 8
Fetching emissions for facility AVLSF... count no 9
Fetching emissions for facility AWABAREF... count no 10
 Failed to fetch emissions for AWABAREF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=AWABAREF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for AWABAREF
Fetching emissions for facility BADGINGARRA... count no 11
 Failed to fetch emissions for BADGINGARRA: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BADGINGARRA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BADGINGARRA
Fetching emissions for facility DEIBDL... count no 12
Fetching emissions for facility BAKING... count no 13
 Failed to fetch emissions for BAKING: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BAKING&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BAKING
Fetching emissions for facility BHWF... count no 14
Fetching emissions for facility BALBESS... count no 15
Fetching emissions for facility BBASEHOS... count no 16
 Failed to fetch emissions for BBASEHOS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BBASEHOS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BBASEHOS
Fetching emissions for facility BANGOWF... count no 17
Fetching emissions for facility BAPS... count no 18
 Failed to fetch emissions for BAPS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BAPS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BAPS
Fetching emissions for facility BANKSPT... count no 19
 Failed to fetch emissions for BANKSPT: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BANKSPT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BANKSPT
Fetching emissions for facility BANNSP... count no 20
Fetching emissions for facility BARCALDN... count no 21
Fetching emissions for facility BARCSF... count no 22
Fetching emissions for facility BARKIPS... count no 23
Fetching emissions for facility BARRON... count no 24
Fetching emissions for facility BASTYAN... count no 25
Fetching emissions for facility BAYSW... count no 26
Fetching emissions for facility BBDISEL1... count no 27
 Failed to fetch emissions for BBDISEL1: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BBDISEL1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BBDISEL1
Fetching emissions for facility BELLBAY... count no 28
 Failed to fetch emissions for BELLBAY: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BELLBAY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BELLBAY
Fetching emissions for facility BBP31... count no 29
Fetching emissions for facility BHBBESS... count no 30
 Failed to fetch emissions for BHBBESS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BHBBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BHBBESS
Fetching emissions for facility BCBESS... count no 31
 Failed to fetch emissions for BCBESS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BCBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BCBESS
Fetching emissions for facility BLAIRFOX_BEROSRD_WF... count no 32
 Failed to fetch emissions for BLAIRFOX_BEROSRD_WF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLAIRFOX_BEROSRD_WF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BLAIRFOX_BEROSRD_WF
Fetching emissions for facility BRYB1WF1... count no 33
Fetching emissions for facility BERWICK... count no 34
 Failed to fetch emissions for BERWICK: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BERWICK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BERWICK
Fetching emissions for facility BERYLSF... count no 35
Fetching emissions for facility BIALAWF... count no 36
Fetching emissions for facility BLAYNEY... count no 37
 Failed to fetch emissions for BLAYNEY: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLAYNEY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BLAYNEY
Fetching emissions for facility BLINDCREEK... count no 38
 Failed to fetch emissions for BLINDCREEK: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLINDCREEK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BLINDCREEK
Fetching emissions for facility SNOWY6... count no 39
Fetching emissions for facility BLUEGSF... count no 40
Fetching emissions for facility BLULAKE... count no 41
 Failed to fetch emissions for BLULAKE: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLULAKE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BLULAKE
Fetching emissions for facility BLUEWATERS... count no 42
 Failed to fetch emissions for BLUEWATERS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLUEWATERS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BLUEWATERS
Fetching emissions for facility BLYTHB... count no 43
Fetching emissions for facility BOCOROCK... count no 44
Fetching emissions for facility BODWF... count no 45
Fetching emissions for facility BOGGABRI... count no 46
 Failed to fetch emissions for BOGGABRI: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BOGGABRI&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BOGGABRI
Fetching emissions for facility MCKAY... count no 47
Fetching emissions for facility BOLIVAR... count no 48
Fetching emissions for facility BOLIVPS... count no 49
Fetching emissions for facility BOMENSF... count no 50
Fetching emissions for facility BCWF... count no 51
 Failed to fetch emissions for BCWF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BCWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BCWF
Fetching emissions for facility BBATTERY... count no 52
Fetching emissions for facility BRAEMARA... count no 53
Fetching emissions for facility B2PS... count no 54
Fetching emissions for facility BREMER_BAY... count no 55
 Failed to fetch emissions for BREMER_BAY: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BREMER_BAY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BREMER_BAY
Fetching emissions for facility BRNDBES... count no 56
Fetching emissions for facility BROADMDW... count no 57
 Failed to fetch emissions for BROADMDW: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BROADMDW&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BROADMDW
Fetching emissions for facility BRDD... count no 58
 Failed to fetch emissions for BRDD: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BRDD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BRDD
Fetching emissions for facility BWTR1... count no 59
Fetching emissions for facility BHILLGT... count no 60
Fetching emissions for facility BROKENH... count no 61
Fetching emissions for facility BHB... count no 62
Fetching emissions for facility BROOKLYN... count no 63
 Failed to fetch emissions for BROOKLYN: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BROOKLYN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BROOKLYN
Fetching emissions for facility BROWNMT... count no 64
 Failed to fetch emissions for BROWNMT: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BROWNMT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BROWNMT
Fetching emissions for facility BPLANDF... count no 65
 Failed to fetch emissions for BPLANDF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BPLANDF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BPLANDF
Fetching emissions for facility WELLINGTONBESS... count no 66
 Failed to fetch emissions for WELLINGTONBESS: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WELLINGTONBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for WELLINGTONBESS
Fetching emissions for facility BULGANA... count no 67
Fetching emissions for facility BUSF... count no 68
 Failed to fetch emissions for BUSF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BUSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BUSF
Fetching emissions for facility BNGSF1... count no 69
Fetching emissions for facility BNGSF2... count no 70
Fetching emissions for facility BUNGAMB... count no 71
 Failed to fetch emissions for BUNGAMB: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BUNGAMB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BUNGAMB
Fetching emissions for facility BDONGHYD... count no 72
 Failed to fetch emissions for BDONGHYD: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BDONGHYD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BDONGHYD
Fetching emissions for facility BURRIN... count no 73
 Failed to fetch emissions for BURRIN: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BURRIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for BURRIN
Fetching emissions for facility BUTLERSG... count no 74
Fetching emissions for facility CALBESS1... count no 75
 Failed to fetch emissions for CALBESS1: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CALBESS1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CALBESS1
Fetching emissions for facility CALBESS2... count no 76
 Failed to fetch emissions for CALBESS2: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CALBESS2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CALBESS2
Fetching emissions for facility CALL_A... count no 77
 Failed to fetch emissions for CALL_A: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CALL_A&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CALL_A
Fetching emissions for facility CALL_B... count no 78
Fetching emissions for facility CALLIDEC1... count no 79
Fetching emissions for facility CANUNDA1... count no 80
Fetching emissions for facility CAPBES... count no 81
Fetching emissions for facility CAPTL_WF... count no 82
Fetching emissions for facility CESF... count no 83
 Failed to fetch emissions for CESF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CESF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CESF
Fetching emissions for facility CARAG... count no 84
 Failed to fetch emissions for CARAG: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CARAG&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CARAG
Fetching emissions for facility CHWF1... count no 85
 Failed to fetch emissions for CHWF1: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CHWF1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CHWF1
Fetching emissions for facility CRWARP... count no 86
 Failed to fetch emissions for CRWARP: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CRWARP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CRWARP
Fetching emissions for facility LI_WY_CA... count no 87
Fetching emissions for facility CATHROCK... count no 88
Fetching emissions for facility CTHLWF... count no 89
Fetching emissions for facility CETHANA... count no 90
Fetching emissions for facility CHALLWF... count no 91
Fetching emissions for facility CHPSTWF... count no 92
 Failed to fetch emissions for CHPSTWF: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CHPSTWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CHPSTWF
Fetching emissions for facility CHYTWF... count no 93
Fetching emissions for facility CHILDSF... count no 94
Fetching emissions for facility CHBESS... count no 95
Fetching emissions for facility CBWWBA... count no 96
Fetching emissions for facility CLARESF... count no 97
Fetching emissions for facility CLRKCWF... count no 98
Fetching emissions for facility CLAYTON... count no 99
 Failed to fetch emissions for CLAYTON: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CLAYTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CLAYTON
Fetching emissions for facility CLEMGPWF... count no 100
Fetching emissions for facility CLERMSF... count no 101
Fetching emissions for facility CLOVER... count no 102
Fetching emissions for facility CLUNY... count no 103
Fetching emissions for facility COCKBURN... count no 104
 Failed to fetch emissions for COCKBURN: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COCKBURN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COCKBURN
Fetching emissions for facility CODRGTON... count no 105
 Failed to fetch emissions for CODRGTON: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CODRGTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for CODRGTON
Fetching emissions for facility COHUNSF1... count no 106
Fetching emissions for facility COLEASF... count no 107
Fetching emissions for facility COLWF01... count no 108
Fetching emissions for facility INVESTEC_COLLGAR... count no 109
 Failed to fetch emissions for INVESTEC_COLLGAR: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=INVESTEC_COLLGAR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for INVESTEC_COLLGAR
Fetching emissions for facility COLLIE... count no 110
 Failed to fetch emissions for COLLIE: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COLLIE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COLLIE
Fetching emissions for facility COLLIE_ESR4... count no 111
 Failed to fetch emissions for COLLIE_ESR4: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COLLIE_ESR4&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COLLIE_ESR4
Fetching emissions for facility COLLIE_ESR... count no 112
 Failed to fetch emissions for COLLIE_ESR: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COLLIE_ESR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COLLIE_ESR
Fetching emissions for facility COLLIE_BESS2... count no 113
 Failed to fetch emissions for COLLIE_BESS2: 404 Client Error: Not Found for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COLLIE_BESS2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
 No data for COLLIE_BESS2
Fetching emissions for facility COLLIE_ESR5... count no 114

### 1.2.3. PER-MARKET POWER PRICE AND DEMAND (5 min interval)

fetches 5-minute market data (spot price and demand) for each network region of the NEM.

In [7]:
NETWORK = "NEM"
NETWORK_REGIONS = ["NSW1", "QLD1", "SA1", "TAS1", "VIC1"]

# SETTINGS
NETWORK_REGIONS = ["NSW1", "QLD1", "SA1", "TAS1", "VIC1"]
METRICS = ["price", "demand"]

def fetch_market_metric(network: str, region: str, metric: str, start: datetime, end: datetime) -> pd.DataFrame:
    
    url = f"{BASE_URL}/market/network/{network}"
    params = {
        "metrics": metric,
        "interval": INTERVAL,
        "network_region": region,
        "date_start": START_DATE,
        "date_end": END_DATE,
    }

    # Request + error handling
    try:
        r = requests.get(url, headers=HEADERS, params=params)
        r.raise_for_status()
        json_data = r.json()
    except Exception as e:
        print(f" Failed {metric.upper()} {region} {start.date()}: {e}")
        return pd.DataFrame()

    # API error response handling
    if not json_data.get("success", False):
        print(f" API returned failure for {metric.upper()} {region}: {json_data.get('error')}")
        return pd.DataFrame()

    # Flatten nested JSON
    rows = []
    for entry in json_data.get("data", []):
        unit = entry.get("unit", "")
        for res in entry.get("results", []):
            for point in res.get("data", []):
                if len(point) == 2:
                    timestamp, value = point
                    rows.append({
                        "timestamp": timestamp,
                        "network": network,
                        "network_region": region,
                        f"value_{metric}": value,
                        f"unit_{metric}": unit,
                    })

    df = pd.DataFrame(rows)
    print(f"SUCCESSFUL {region}: {metric.upper()} {start.date()} → {len(df)} rows")
    return df



# Collect one day at a time to avoid overwhelming API
all_data = []
current_date = START_DATE

while current_date < END_DATE:
    next_date = current_date + timedelta(days=1)

    for region in NETWORK_REGIONS:
        region_data = []
        for metric in METRICS:
            df = fetch_market_metric(NETWORK, region, metric, current_date, next_date)
            if not df.empty:
                region_data.append(df)

        # Merge price + demand for this region/day
        if region_data:
            merged_df = region_data[0]
            for df in region_data[1:]:
                merged_df = pd.merge(
                    merged_df,
                    df,
                    on=["timestamp", "network", "network_region"],
                    how="outer"
                )
            all_data.append(merged_df)

    current_date = next_date
    
# Final concatenation of all data
if not all_data:
    print(" No market data retrieved for any region or day.")
 
market_raw = pd.concat(all_data, ignore_index=True)

SUCCESSFUL NSW1: PRICE 2025-10-01 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-01 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-01 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-01 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-01 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-01 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-01 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-01 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-01 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-01 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-02 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-02 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-02 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-02 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-02 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-02 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-02 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-02 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-02 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-02 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-03 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-03 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-03 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-03 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-03 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-03 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-03 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-03 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-03 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-03 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-04 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-04 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-04 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-04 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-04 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-04 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-04 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-04 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-04 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-04 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-05 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-05 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-05 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-05 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-05 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-05 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-05 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-05 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-05 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-05 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-06 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-06 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-06 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-06 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-06 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-06 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-06 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-06 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-06 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-06 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-07 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-07 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-07 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-07 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-07 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-07 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-07 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-07 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-07 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-07 → 2016 rows

## 1.3. RAW dataframes list

In [8]:
facilities_df

,name,network_id,network_region,description,location,code,units,created_at,updated_at
0,Adelaide Desalination,NEM,SA1,"<p>The Adelaide Desalination plant (ADP), form...","{'lat': -35.096948, 'lng': 138.484061}",ADP,"[{'code': 'ADPBA1G', 'code_display': '0ADPBA1G...",2023-10-18T04:34:30Z,2026-06-23T03:48:08Z
1,Albany,WEM,WEM,<p>Albany wind and Grasmere farms are two wind...,"{'lat': -35.055759, 'lng': 117.777048}",ALBANY,"[{'code': 'ALBANY_WF1', 'code_display': 'ALBAN...",2023-10-18T04:34:30Z,2026-08-14T00:15:29Z
2,Aldoga,NEM,QLD1,<p>The Aldoga Solar Farm will be approximately...,"{'lat': -23.815177, 'lng': 151.05811}",ALDGASF,"[{'code': 'ALDGASF1', 'code_display': 'ALDGASF...",2025-01-31T04:19:33Z,2026-08-14T00:15:29Z
3,Amcor Glass,NEM,SA1,<p></p>,"{'lat': -34.847716, 'lng': 138.581503}",AMCORGR,"[{'code': 'AMCORGR', 'code_display': 'AMCORGR'...",2023-10-18T04:34:32Z,2026-08-14T00:15:44Z
4,Angaston,NEM,SA1,<p>Angaston Power Station is a diesel-powered ...,"{'lat': -34.503389, 'lng': 139.02458}",ANGASTON,"[{'code': 'ANGAST1', 'code_display': 'ANGAST1'...",2023-10-18T04:34:32Z,2026-06-16T04:42:05Z
...,...,...,...,...,...,...,...,...,...
620,Yarrawonga,NEM,VIC1,<p>Yarrawonga Power Station is adjacent to the...,"{'lat': -36.009466, 'lng': 145.999568}",YWNGAHYD,"[{'code': 'YWNGAHYD', 'code_display': 'YWNGAHY...",2023-10-18T04:35:33Z,2026-03-20T03:55:57Z
621,Yarwun,NEM,QLD1,<p></p>,"{'lat': -23.8309, 'lng': 151.151136}",YARWUN,"[{'code': 'YARWUN_1', 'code_display': 'YARWUN_...",2023-10-18T04:35:33Z,2026-03-17T23:52:47Z
622,Yatpool,NEM,VIC1,<p>The 258-hectare Yatpool Solar Farm in north...,"{'lat': -34.396363, 'lng': 142.173809}",YATSF1,"[{'code': 'YATSF1', 'code_display': 'YATSF1', ...",2023-10-18T04:35:33Z,2026-03-19T03:44:32Z
623,Yawong,NEM,VIC1,<p>The Yawong Wind Farm was developed and cons...,"{'lat': -36.481161, 'lng': 143.366605}",YAWWF,"[{'code': 'YAWWF1', 'code_display': 'YAWWF1', ...",2023-10-18T04:35:33Z,2026-08-14T00:15:42Z
624,Yendon,NEM,VIC1,"<p>Lal Lal Wind Farms, which consists of the a...","{'lat': -37.630407, 'lng': 144.023136}",YENDONWF,"[{'code': 'YENDWF1', 'code_display': 'YENDWF1'...",2023-10-18T04:35:33Z,2026-06-30T05:49:21Z

In [9]:
power_df_raw

        facility_id unit_code                  timestamp  power_MW
0               ADP        MW  2025-10-01T00:00:00+10:00    -0.004
1               ADP        MW  2025-10-01T00:05:00+10:00    -0.046
2               ADP        MW  2025-10-01T00:10:00+10:00     0.000
3               ADP        MW  2025-10-01T00:15:00+10:00     0.003
4               ADP        MW  2025-10-01T00:20:00+10:00    -0.018
...             ...       ...                        ...       ...
1084360    YENDONWF        MW  2025-10-07T23:35:00+10:00    88.630
1084361    YENDONWF        MW  2025-10-07T23:40:00+10:00    91.890
1084362    YENDONWF        MW  2025-10-07T23:45:00+10:00    89.030
1084363    YENDONWF        MW  2025-10-07T23:50:00+10:00    85.830
1084364    YENDONWF        MW  2025-10-07T23:55:00+10:00    89.870

[1084365 rows x 4 columns]

In [10]:
emissions_df_raw

        facility_id unit_code                  timestamp  emission
0               ADP         t  2025-10-01T00:00:00+10:00       0.0
1               ADP         t  2025-10-01T00:05:00+10:00       0.0
2               ADP         t  2025-10-01T00:10:00+10:00       0.0
3               ADP         t  2025-10-01T00:15:00+10:00       0.0
4               ADP         t  2025-10-01T00:20:00+10:00       0.0
...             ...       ...                        ...       ...
1084360    YENDONWF         t  2025-10-07T23:35:00+10:00       0.0
1084361    YENDONWF         t  2025-10-07T23:40:00+10:00       0.0
1084362    YENDONWF         t  2025-10-07T23:45:00+10:00       0.0
1084363    YENDONWF         t  2025-10-07T23:50:00+10:00       0.0
1084364    YENDONWF         t  2025-10-07T23:55:00+10:00       0.0

[1084365 rows x 4 columns]

In [11]:
market_raw

,timestamp,network,network_region,value_price,unit_price,value_demand,unit_demand
0,2025-10-01T00:00:00+10:00,NEM,NSW1,56.98,$/MWh,7105.57,MW
1,2025-10-01T00:05:00+10:00,NEM,NSW1,80.01,$/MWh,7170.68,MW
2,2025-10-01T00:10:00+10:00,NEM,NSW1,58.40,$/MWh,7158.50,MW
3,2025-10-01T00:15:00+10:00,NEM,NSW1,80.01,$/MWh,7177.80,MW
4,2025-10-01T00:20:00+10:00,NEM,NSW1,65.00,$/MWh,7085.54,MW
...,...,...,...,...,...,...,...
70555,2025-10-07T23:35:00+10:00,NEM,VIC1,104.22,$/MWh,4709.39,MW
70556,2025-10-07T23:40:00+10:00,NEM,VIC1,103.68,$/MWh,4696.86,MW
70557,2025-10-07T23:45:00+10:00,NEM,VIC1,95.86,$/MWh,4639.93,MW
70558,2025-10-07T23:50:00+10:00,NEM,VIC1,95.88,$/MWh,4616.01,MW
70559,2025-10-07T23:55:00+10:00,NEM,VIC1,82.83,$/MWh,4576.42,MW

# 2. DATA INTEGRATION/CLEANING

## 2.1. Cleaning and Combining Power-Emission

Merge facility power and emissions data on facility ID and timestamp. Outer join keeps rows even if power or emissions is missing for a time period

In [12]:
power_emission_raw_stage_1 = pd.merge(
    power_df_raw,
    emissions_df_raw,
    on=['facility_id', 'timestamp'],
    how='outer' 
).sort_values(by=['timestamp','facility_id']).reset_index(drop=True)
print(power_emission_raw_stage_1)

        facility_id unit_code_x                  timestamp  power_MW  \
0               ADP          MW  2025-10-01T00:00:00+10:00    -0.004
1               ADP          MW  2025-10-01T00:00:00+10:00    -0.004
2               ADP          MW  2025-10-01T00:00:00+10:00    -0.004
3               ADP          MW  2025-10-01T00:00:00+10:00     0.000
4               ADP          MW  2025-10-01T00:00:00+10:00     0.000
...             ...         ...                        ...       ...
2425586     YARANSF          MW  2025-10-07T23:55:00+10:00     0.000
2425587      YARWUN          MW  2025-10-07T23:55:00+10:00   138.990
2425588      YATSF1          MW  2025-10-07T23:55:00+10:00     0.000
2425589    YENDONWF          MW  2025-10-07T23:55:00+10:00    89.870
2425590        YSWF          MW  2025-10-07T23:55:00+10:00    11.600

        unit_code_y  emission
0                 t    0.0000
1                 t    0.0000
2                 t    0.0000
3                 t    0.0000
4                 t    0.0000
...             ...       ...
2425586           t    0.0000
2425587           t    7.1011
2425588           t    0.0000
2425589           t    0.0000
2425590           t    0.0000

[2425591 rows x 6 columns]

Here we :
- Take absolute value of Power since some Power is in -ve which cannot be true for a power plant

- drop redundant columns
- drop rows with 0 in both power and emission

In [13]:
power_emission_raw_stage_1['power_in_MW'] = power_emission_raw_stage_1['power_MW'].abs()
power_emission_raw_stage_1 = power_emission_raw_stage_1[~((power_emission_raw_stage_1['power_MW'] == 0) & (power_emission_raw_stage_1['emission'] == 0))]
power_emission_raw_stage_1 = power_emission_raw_stage_1.drop(columns=[col for col in ['unit_code_x', 'unit_code_y','power_MW'] if col in power_emission_raw_stage_1.columns])


print(power_emission_raw_stage_1.reset_index(drop=True))

        facility_id                  timestamp  emission  power_in_MW
0               ADP  2025-10-01T00:00:00+10:00    0.0000        0.004
1               ADP  2025-10-01T00:00:00+10:00    0.0000        0.004
2               ADP  2025-10-01T00:00:00+10:00    0.0000        0.004
3               ADP  2025-10-01T00:00:00+10:00    0.0000        0.004
4               ADP  2025-10-01T00:00:00+10:00    0.0000        0.004
...             ...                        ...       ...          ...
1586412    YALLOURN  2025-10-07T23:55:00+10:00   38.9360        0.000
1586413      YAMBUK  2025-10-07T23:55:00+10:00    0.0000       14.600
1586414      YARWUN  2025-10-07T23:55:00+10:00    7.1011      138.990
1586415    YENDONWF  2025-10-07T23:55:00+10:00    0.0000       89.870
1586416        YSWF  2025-10-07T23:55:00+10:00    0.0000       11.600

[1586417 rows x 4 columns]

In [14]:

# Round to 3 decimal places (numeric precision)
power_emission_raw_stage_1["power_in_MW"] = power_emission_raw_stage_1["power_in_MW"].round(3)
power_emission_raw_stage_1["emission"] = power_emission_raw_stage_1["emission"].round(3)

# Format to always show exactly 3 decimal places
power_emission_raw_stage_1["power_in_MW"] = power_emission_raw_stage_1["power_in_MW"].map(lambda x: f"{x:.3f}")
power_emission_raw_stage_1["emission"] = power_emission_raw_stage_1["emission"].map(lambda x: f"{x:.3f}")

# Remove duplicates where timestamp, power, and emission are the same
power_emission_raw_stage_2 = power_emission_raw_stage_1.drop_duplicates(
    subset=["timestamp", "power_in_MW", "emission"]
).reset_index(drop=True)

power_emission_raw_stage_2

       facility_id                  timestamp emission power_in_MW
0              ADP  2025-10-01T00:00:00+10:00    0.000       0.004
1             ARWF  2025-10-01T00:00:00+10:00    0.000      35.400
2             B2PS  2025-10-01T00:00:00+10:00    0.004       0.081
3             B2PS  2025-10-01T00:00:00+10:00    0.000       0.081
4             B2PS  2025-10-01T00:00:00+10:00    0.004       0.000
...            ...                        ...      ...         ...
771373    YALLOURN  2025-10-07T23:55:00+10:00   38.936     360.562
771374      YAMBUK  2025-10-07T23:55:00+10:00    0.000      14.600
771375      YARWUN  2025-10-07T23:55:00+10:00    7.101     138.990
771376    YENDONWF  2025-10-07T23:55:00+10:00    0.000      89.870
771377        YSWF  2025-10-07T23:55:00+10:00    0.000      11.600

[771378 rows x 4 columns]

## 2.2. Cleaning Facilities

In [15]:
facilities_df

,name,network_id,network_region,description,location,code,units,created_at,updated_at
0,Adelaide Desalination,NEM,SA1,"<p>The Adelaide Desalination plant (ADP), form...","{'lat': -35.096948, 'lng': 138.484061}",ADP,"[{'code': 'ADPBA1G', 'code_display': '0ADPBA1G...",2023-10-18T04:34:30Z,2026-06-23T03:48:08Z
1,Albany,WEM,WEM,<p>Albany wind and Grasmere farms are two wind...,"{'lat': -35.055759, 'lng': 117.777048}",ALBANY,"[{'code': 'ALBANY_WF1', 'code_display': 'ALBAN...",2023-10-18T04:34:30Z,2026-08-14T00:15:29Z
2,Aldoga,NEM,QLD1,<p>The Aldoga Solar Farm will be approximately...,"{'lat': -23.815177, 'lng': 151.05811}",ALDGASF,"[{'code': 'ALDGASF1', 'code_display': 'ALDGASF...",2025-01-31T04:19:33Z,2026-08-14T00:15:29Z
3,Amcor Glass,NEM,SA1,<p></p>,"{'lat': -34.847716, 'lng': 138.581503}",AMCORGR,"[{'code': 'AMCORGR', 'code_display': 'AMCORGR'...",2023-10-18T04:34:32Z,2026-08-14T00:15:44Z
4,Angaston,NEM,SA1,<p>Angaston Power Station is a diesel-powered ...,"{'lat': -34.503389, 'lng': 139.02458}",ANGASTON,"[{'code': 'ANGAST1', 'code_display': 'ANGAST1'...",2023-10-18T04:34:32Z,2026-06-16T04:42:05Z
...,...,...,...,...,...,...,...,...,...
620,Yarrawonga,NEM,VIC1,<p>Yarrawonga Power Station is adjacent to the...,"{'lat': -36.009466, 'lng': 145.999568}",YWNGAHYD,"[{'code': 'YWNGAHYD', 'code_display': 'YWNGAHY...",2023-10-18T04:35:33Z,2026-03-20T03:55:57Z
621,Yarwun,NEM,QLD1,<p></p>,"{'lat': -23.8309, 'lng': 151.151136}",YARWUN,"[{'code': 'YARWUN_1', 'code_display': 'YARWUN_...",2023-10-18T04:35:33Z,2026-03-17T23:52:47Z
622,Yatpool,NEM,VIC1,<p>The 258-hectare Yatpool Solar Farm in north...,"{'lat': -34.396363, 'lng': 142.173809}",YATSF1,"[{'code': 'YATSF1', 'code_display': 'YATSF1', ...",2023-10-18T04:35:33Z,2026-03-19T03:44:32Z
623,Yawong,NEM,VIC1,<p>The Yawong Wind Farm was developed and cons...,"{'lat': -36.481161, 'lng': 143.366605}",YAWWF,"[{'code': 'YAWWF1', 'code_display': 'YAWWF1', ...",2023-10-18T04:35:33Z,2026-08-14T00:15:42Z
624,Yendon,NEM,VIC1,"<p>Lal Lal Wind Farms, which consists of the a...","{'lat': -37.630407, 'lng': 144.023136}",YENDONWF,"[{'code': 'YENDWF1', 'code_display': 'YENDWF1'...",2023-10-18T04:35:33Z,2026-06-30T05:49:21Z

In [16]:
# Step 1: Drop unwanted columns 
facilities_df_stage_1 = facilities_df.drop(columns=['description', 'created_at', 'updated_at'], errors='ignore')

# Step 2: Split 'location' dict into latitude and longitude
# If 'location' is a string, convert to dict first
facilities_df_stage_1['location'] = facilities_df_stage_1['location'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)
facilities_df_stage_1['latitude'] = facilities_df_stage_1['location'].apply(lambda x: x.get('lat') if isinstance(x, dict) else None)
facilities_df_stage_1['longitude'] = facilities_df_stage_1['location'].apply(lambda x: x.get('lng') if isinstance(x, dict) else None)
facilities_df_stage_1 = facilities_df_stage_1.drop(columns=['location'])

#  Clean 'network_region' (remove trailing '1') 
facilities_df_stage_1['network_region'] = facilities_df_stage_1['network_region'].str.replace(r'1$', '', regex=True)

# Step 4: Extract first 'fueltech_id' from 'units' list 
# Convert stringified lists to Python lists (if needed)
facilities_df_stage_1['units'] = facilities_df_stage_1['units'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)
facilities_df_stage_1['fuel_source'] = facilities_df_stage_1['units'].apply(
    lambda x: x[0]['fueltech_id'] if isinstance(x, list) and len(x) > 0 else None
)

# Optional: Drop original 'units' column if no longer needed
#facilities_df_stage_1 = facilities_df_stage_1.drop(columns=['units'])

# Final cleaned DataFrame
print(facilities_df_stage_1)

                      name network_id network_region      code  \
0    Adelaide Desalination        NEM             SA       ADP
1                   Albany        WEM            WEM    ALBANY
2                   Aldoga        NEM            QLD   ALDGASF
3              Amcor Glass        NEM             SA   AMCORGR
4                 Angaston        NEM             SA  ANGASTON
..                     ...        ...            ...       ...
620             Yarrawonga        NEM            VIC  YWNGAHYD
621                 Yarwun        NEM            QLD    YARWUN
622                Yatpool        NEM            VIC    YATSF1
623                 Yawong        NEM            VIC     YAWWF
624                 Yendon        NEM            VIC  YENDONWF

                                                 units   latitude   longitude  \
0    [{'code': 'ADPBA1G', 'code_display': '0ADPBA1G... -35.096948  138.484061
1    [{'code': 'ALBANY_WF1', 'code_display': 'ALBAN... -35.055759  117.777048
2    [{'code': 'ALDGASF1', 'code_display': 'ALDGASF... -23.815177  151.058110
3    [{'code': 'AMCORGR', 'code_display': 'AMCORGR'... -34.847716  138.581503
4    [{'code': 'ANGAST1', 'code_display': 'ANGAST1'... -34.503389  139.024580
..                                                 ...        ...         ...
620  [{'code': 'YWNGAHYD', 'code_display': 'YWNGAHY... -36.009466  145.999568
621  [{'code': 'YARWUN_1', 'code_display': 'YARWUN_... -23.830900  151.151136
622  [{'code': 'YATSF1', 'code_display': 'YATSF1', ... -34.396363  142.173809
623  [{'code': 'YAWWF1', 'code_display': 'YAWWF1', ... -36.481161  143.366605
624  [{'code': 'YENDWF1', 'code_display': 'YENDWF1'... -37.630407  144.023136

             fuel_source
0    battery_discharging
1                   wind
2          solar_utility
3             distillate
4             distillate
..                   ...
620                hydro
621             gas_ccgt
622        solar_utility
623                 wind
624                 wind

[625 rows x 8 columns]

## 2.3. Combine facilities and power-emission

Left-Join facility attributes (name, region, location etc.) onto the power-emissions data

In [17]:
power_emission_raw_stage_3 = pd.merge(
    power_emission_raw_stage_2,
    facilities_df_stage_1,
    how='left',
    left_on='facility_id',
    right_on='code'
)

In [18]:
power_emission_raw_stage_3

,facility_id,timestamp,emission,power_in_MW,name,network_id,network_region,code,units,latitude,longitude,fuel_source
0,ADP,2025-10-01T00:00:00+10:00,0.000,0.004,Adelaide Desalination,NEM,SA,ADP,"[{'code': 'ADPBA1G', 'code_display': '0ADPBA1G...",-35.096948,138.484061,battery_discharging
1,ARWF,2025-10-01T00:00:00+10:00,0.000,35.400,Ararat,NEM,VIC,ARWF,"[{'code': 'ARWF1', 'code_display': 'ARWF1', 'f...",-37.238714,143.079243,wind
2,B2PS,2025-10-01T00:00:00+10:00,0.004,0.081,Braemar 2,NEM,QLD,B2PS,"[{'code': 'BRAEMAR6', 'code_display': 'BRAEMAR...",-27.112874,150.905442,gas_ocgt
3,B2PS,2025-10-01T00:00:00+10:00,0.000,0.081,Braemar 2,NEM,QLD,B2PS,"[{'code': 'BRAEMAR6', 'code_display': 'BRAEMAR...",-27.112874,150.905442,gas_ocgt
4,B2PS,2025-10-01T00:00:00+10:00,0.004,0.000,Braemar 2,NEM,QLD,B2PS,"[{'code': 'BRAEMAR6', 'code_display': 'BRAEMAR...",-27.112874,150.905442,gas_ocgt
...,...,...,...,...,...,...,...,...,...,...,...,...
771373,YALLOURN,2025-10-07T23:55:00+10:00,38.936,360.562,Yallourn W,NEM,VIC,YALLOURN,"[{'code': 'YWPS4', 'code_display': 'YWPS4', 'f...",-38.177589,146.342556,coal_brown
771374,YAMBUK,2025-10-07T23:55:00+10:00,0.000,14.600,Yambuk,NEM,VIC,YAMBUK,"[{'code': 'YAMBUKWF', 'code_display': 'YAMBUKW...",-38.310953,142.014788,wind
771375,YARWUN,2025-10-07T23:55:00+10:00,7.101,138.990,Yarwun,NEM,QLD,YARWUN,"[{'code': 'YARWUN_1', 'code_display': 'YARWUN_...",-23.830900,151.151136,gas_ccgt
771376,YENDONWF,2025-10-07T23:55:00+10:00,0.000,89.870,Yendon,NEM,VIC,YENDONWF,"[{'code': 'YENDWF1', 'code_display': 'YENDWF1'...",-37.630407,144.023136,wind
771377,YSWF,2025-10-07T23:55:00+10:00,0.000,11.600,Yaloak South,NEM,VIC,YSWF,"[{'code': 'YSWF1', 'code_display': 'YSWF1', 'f...",-37.726107,144.255041,wind

In [19]:
power_emission_raw_stage_4 = power_emission_raw_stage_3.drop(columns=["network_id", "code"])
print(power_emission_raw_stage_4)

       facility_id                  timestamp emission power_in_MW  \
0              ADP  2025-10-01T00:00:00+10:00    0.000       0.004
1             ARWF  2025-10-01T00:00:00+10:00    0.000      35.400
2             B2PS  2025-10-01T00:00:00+10:00    0.004       0.081
3             B2PS  2025-10-01T00:00:00+10:00    0.000       0.081
4             B2PS  2025-10-01T00:00:00+10:00    0.004       0.000
...            ...                        ...      ...         ...
771373    YALLOURN  2025-10-07T23:55:00+10:00   38.936     360.562
771374      YAMBUK  2025-10-07T23:55:00+10:00    0.000      14.600
771375      YARWUN  2025-10-07T23:55:00+10:00    7.101     138.990
771376    YENDONWF  2025-10-07T23:55:00+10:00    0.000      89.870
771377        YSWF  2025-10-07T23:55:00+10:00    0.000      11.600

                         name network_region  \
0       Adelaide Desalination             SA
1                      Ararat            VIC
2                   Braemar 2            QLD
3                   Braemar 2            QLD
4                   Braemar 2            QLD
...                       ...            ...
771373             Yallourn W            VIC
771374                 Yambuk            VIC
771375                 Yarwun            QLD
771376                 Yendon            VIC
771377           Yaloak South            VIC

                                                    units   latitude  \
0       [{'code': 'ADPBA1G', 'code_display': '0ADPBA1G... -35.096948
1       [{'code': 'ARWF1', 'code_display': 'ARWF1', 'f... -37.238714
2       [{'code': 'BRAEMAR6', 'code_display': 'BRAEMAR... -27.112874
3       [{'code': 'BRAEMAR6', 'code_display': 'BRAEMAR... -27.112874
4       [{'code': 'BRAEMAR6', 'code_display': 'BRAEMAR... -27.112874
...                                                   ...        ...
771373  [{'code': 'YWPS4', 'code_display': 'YWPS4', 'f... -38.177589
771374  [{'code': 'YAMBUKWF', 'code_display': 'YAMBUKW... -38.310953
771375  [{'code': 'YARWUN_1', 'code_display': 'YARWUN_... -23.830900
771376  [{'code': 'YENDWF1', 'code_display': 'YENDWF1'... -37.630407
771377  [{'code': 'YSWF1', 'code_display': 'YSWF1', 'f... -37.726107

         longitude          fuel_source
0       138.484061  battery_discharging
1       143.079243                 wind
2       150.905442             gas_ocgt
3       150.905442             gas_ocgt
4       150.905442             gas_ocgt
...            ...                  ...
771373  146.342556           coal_brown
771374  142.014788                 wind
771375  151.151136             gas_ccgt
771376  144.023136                 wind
771377  144.255041                 wind

[771378 rows x 10 columns]

For Final Cleanup, we drop duplicates

In [20]:

power_emission_final = power_emission_raw_stage_4.drop_duplicates(
    subset=['facility_id', 'timestamp'],
    keep='first'  # or 'last' if you want to keep the last occurrence
)

# Optional: reset index
power_emission_final.reset_index(drop=True, inplace=True)

## 2.4. Price and Demand Cleanup

Clean Up Per Market Price and Demand

In [21]:
market_raw_stage_1 =market_raw

In [22]:
# Remove the trailing '1' from region codes (e.g., 'NSW1' to 'NSW')
market_raw_stage_1['network_region'] = market_raw_stage_1['network_region'].str.replace(r'1$', '', regex=True)

In [23]:
# Remove duplicate timestamp rows to avoid double counting price/demand
market_raw_stage_1 = market_raw_stage_1.drop_duplicates(
    subset=["timestamp", "value_price", "value_demand"]
).reset_index(drop=True)


# Drop network column (not needed after region-level aggregation)
market_raw_stage_2 = market_raw_stage_1.drop(columns=["network"])

# Rename metric columns and drop unit columns since units are implied
market_raw_stage_2 = market_raw_stage_2.rename(
    columns={
        "value_price": "value_price_in_$/MWh",
        "value_demand": "value_demand_in_MW"
    }
).drop(columns=["unit_price", "unit_demand"])
# Force all price and demand values to positive (market data sometimes returns signed numbers)
market_raw_stage_2["value_price_in_$/MWh"] = market_raw_stage_2["value_price_in_$/MWh"].abs()
market_raw_stage_2["value_demand_in_MW"] = market_raw_stage_2["value_demand_in_MW"].abs()

In [24]:
# Sort market data chronologically and by region for consistent merging
market_raw_stage_3 = market_raw_stage_2.sort_values(
    by=["timestamp", "network_region"]
).reset_index(drop=True)

## 2.5. Merging Power and Market Datasets

In [25]:
# Merge facility time-series data with market price & demand based on timestamp and region
merged_df = pd.merge(
    power_emission_final,market_raw_stage_3
    [["timestamp", "network_region", "value_price_in_$/MWh", "value_demand_in_MW"]],
    on=["timestamp", "network_region"],
    how="left"
)

# Quick sanity check
print("Merged shape:", merged_df.shape)
merged_df.head(5)

Merged shape: (412486, 12)

,facility_id,timestamp,emission,power_in_MW,name,network_region,units,latitude,longitude,fuel_source,value_price_in_$/MWh,value_demand_in_MW
0,ADP,2025-10-01T00:00:00+10:00,0.000,0.004,Adelaide Desalination,SA,"[{'code': 'ADPBA1G', 'code_display': '0ADPBA1G...",-35.096948,138.484061,battery_discharging,8.11,1564.92
1,ARWF,2025-10-01T00:00:00+10:00,0.000,35.400,Ararat,VIC,"[{'code': 'ARWF1', 'code_display': 'ARWF1', 'f...",-37.238714,143.079243,wind,8.95,4893.49
2,B2PS,2025-10-01T00:00:00+10:00,0.004,0.081,Braemar 2,QLD,"[{'code': 'BRAEMAR6', 'code_display': 'BRAEMAR...",-27.112874,150.905442,gas_ocgt,54.82,5989.24
3,BANGOWF,2025-10-01T00:00:00+10:00,0.000,97.699,Bango,NSW,"[{'code': 'BANGOWF2', 'code_display': 'BANGOWF...",-34.767208,148.921499,wind,56.98,7105.57
4,BARCSF,2025-10-01T00:00:00+10:00,0.000,0.100,Barcaldine,QLD,"[{'code': 'BARCSF1', 'code_display': 'BARCSF1'...",-23.547776,145.318817,solar_utility,54.82,5989.24

In [26]:
# Save to a new CSV for use in Stage 3
merged_df.to_csv("power_emission.csv", index=False)

# 3. Data Publishing via MQTT

## 3.1. MQTT configs and setup

In [27]:
MQTT_BROKER = "test.mosquitto.org"
MQTT_PORT   = 1883
TOPIC_POWER = "470461201/A2"  # topic for pub./sub
PUBLISH_DELAY = 0.1         # seconds between messages  
RELOAD_DELAY  = 0          # seconds to wait between rounds when REPEAT=True
END_WAIT_SECS = 60           # wait before replay restart
REPEAT = True                # keep publishing in a loop

## 3.2. Transforming Facilities Unit Data

Parsing and Extracting Unit Codes from Facility Metadata

In [28]:
def parse_units_codes(units_cell):
    """Return ONLY the 'code' values from the 'units' JSON."""
    if units_cell is None or (isinstance(units_cell, float) and pd.isna(units_cell)):
        return []
    obj = units_cell
    # If stored as a string (JSON or Python literal), try to parse it
    if isinstance(units_cell, str):
        s = units_cell.strip()
        if not s:
            return []
        try:
            obj = json.loads(s) #JSON
        except Exception:
            try:
                obj = ast.literal_eval(s) #Python
            except Exception:
                return []
    # Ensure we are working with a list of dicts
    if isinstance(obj, dict):
        obj = [obj]
    if not isinstance(obj, (list, tuple)):
        return []
    return [str(d.get("code")) for d in obj if isinstance(d, dict) and d.get("code")]

CSV_PATH = "power_emission.csv"
power_df = pd.read_csv(CSV_PATH)

# Extract clean list of codes and a display-friendly string
power_df["unit_codes"] = power_df["units"].apply(parse_units_codes)
power_df["unit_codes_str"] = power_df["unit_codes"].apply(lambda xs: ", ".join(xs) if xs else "—")

display(power_df[["facility_id","name","unit_codes","unit_codes_str"]].head(5))
# Ensure timestamps are datetime objects
power_df["timestamp"] = pd.to_datetime(power_df["timestamp"])

,facility_id,name,unit_codes,unit_codes_str
0,ADP,Adelaide Desalination,"[ADPBA1G, ADPBA1L, ADPBA1, ADPPV1, ADPPV2, ADP...","ADPBA1G, ADPBA1L, ADPBA1, ADPPV1, ADPPV2, ADPP..."
1,ARWF,Ararat,[ARWF1],ARWF1
2,B2PS,Braemar 2,"[BRAEMAR6, BRAEMAR5, BRAEMAR7]","BRAEMAR6, BRAEMAR5, BRAEMAR7"
3,BANGOWF,Bango,"[BANGOWF2, BANGOWF1]","BANGOWF2, BANGOWF1"
4,BARCSF,Barcaldine,[BARCSF1],BARCSF1

Initializing MQTT Client and Publish Callback

In [29]:
client = mqtt.Client()
client.connect(MQTT_BROKER, MQTT_PORT, 60)
client.loop_start()

def on_publish(client, userdata, mid):
    print(f"MQTT message with mid={mid} successfully published.")

client.on_publish = on_publish

/var/folders/0x/p1c52y6d1z57g2cq5s9yfqk40000gn/T/ipykernel_65636/3426122455.py:1: DeprecationWarning: Callback API version 1 is deprecated, update to latest version
  client = mqtt.Client()

## 3.3. Publisher Setup (5. Continuous Execution)

Publishing Time-Series Power and Emissions Data as MQTT Stream. Duplicaton Avoided and Continuous Execution Executed

In [30]:
def publish_stream(power_df, delay_between_messages=PUBLISH_DELAY, delay_between_timestamps=RELOAD_DELAY):
    all_timestamps = sorted(power_df["timestamp"].unique())

    for ts in all_timestamps:
        print(f"\nPublishing data for timestamp: {ts}")

        # Pulling and Sending Data
        subset_power = power_df[power_df["timestamp"] == ts]
        for _, row in subset_power.iterrows():
            # To improve latency, ignoring row if power and emission are 0
            power_val    = float(row.get("power_in_MW", 0) or 0)
            emission_val = float(row.get("emission",    0) or 0)
            if power_val == 0 and emission_val == 0:
                continue 
            
            # Message Data
            msg_power = {
                "facility_id": row["facility_id"],
                "name": row["name"],
                "timestamp": str(row["timestamp"]),
                "power_MW": power_val,
                "emissions_tCO2": emission_val,
                "network_region": row["network_region"],
                "fuel_source": row["fuel_source"],
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
                "value_price_in_$/MWh": float(row.get("value_price_in_$/MWh")),
                "value_demand_in_MW": float(row.get("value_demand_in_MW")),
                "unit_codes": row.get("unit_codes"),
                "unit_codes_str": row.get("unit_codes_str")
            }
            client.publish(TOPIC_POWER, json.dumps(msg_power))
            print(f" Power published: {msg_power['facility_id']} ({msg_power['power_MW']} MW)")
            #Delay between messages is 0.1s
            time.sleep(delay_between_messages)

        #Delay between timestamp batches is 0s, can be set by changing RELOAD_DELAY 
        print(f"Finished timestamp {ts}. Waiting {delay_between_timestamps}s before next batch...")
        time.sleep(delay_between_timestamps)
      
    #Continous Execution, if we run out of data, we wait for 60s and replay the dataset again
    if REPEAT:
        print(f"End of data reached. Waiting {END_WAIT_SECS}s before restarting...")
        time.sleep(END_WAIT_SECS)
        publish_stream(power_df)
        return

## 3.4. Running Publisher

Publishing the Data

In [31]:
try:
    publish_stream(power_df)
except KeyboardInterrupt:
    print("\n Streaming stopped by user.")
finally:
    client.loop_stop()
    client.disconnect()
    print(" MQTT client disconnected")

Publishing data for timestamp: 2025-10-01 00:00:00+10:00
 Power published: ADP (0.004 MW)
MQTT message with mid=1 successfully published.
 Power published: ARWF (35.4 MW)
MQTT message with mid=2 successfully published.
 Power published: B2PS (0.081 MW)
MQTT message with mid=3 successfully published.
 Power published: BANGOWF (97.699 MW)
MQTT message with mid=4 successfully published.
 Power published: BARCSF (0.1 MW)MQTT message with mid=5 successfully published.

 Power published: BASTYAN (57.1 MW)
MQTT message with mid=6 successfully published.
 Power published: BAYSW (558.395 MW)MQTT message with mid=7 successfully published.

 Power published: BBATTERY (0.015 MW)
MQTT message with mid=8 successfully published.
 Power published: BHB (2.194 MW)MQTT message with mid=9 successfully published.

 Power published: BHWF (7.764 MW)
MQTT message with mid=10 successfully published.
 Power published: BIALAWF (69.172 MW)
MQTT message with mid=11 successfully published.
 Power published: BLUEGSF (0.101 MW)
MQTT message with mid=12 successfully published.
 Power published: BLUFF (46.5 MW)
MQTT message with mid=13 successfully published.
 Power published: BLYTHB (0.44 MW)
MQTT message with mid=14 successfully published.
 Power published: BOCOROCK (54.23 MW)
MQTT message with mid=15 successfully published.
 Power published: BODWF (45.192 MW)
MQTT message with mid=16 successfully published.
 Power published: BRNDBES (0.137 MW)
MQTT message with mid=17 successfully published.
 Power published: BRYB1WF1 (126.879 MW)
MQTT message with mid=18 successfully published.
 Power published: BULGANA (0.13 MW)MQTT message with mid=19 successfully published.

 Power published: BUTLERSG (6.4 MW)
MQTT message with mid=20 successfully published.
 Power published: BWTR1 (25.322 MW)
MQTT message with mid=21 successfully published.
 Power published: CALLIDEC1 (0.0 MW)
MQTT message with mid=22 successfully published.
 Power published: CALL_B (279.2 MW)
MQTT message with mid=23 successfully published.
 Power published: CANUNDA1 (26.931 MW)
MQTT message with mid=24 successfully published.
 Power published: CAPBES (1.25 MW)
MQTT message with mid=25 successfully published.
 Power published: CAPTL_WF (114.295 MW)
MQTT message with mid=26 successfully published.
 Power published: CATHROCK (40.0 MW)
MQTT message with mid=27 successfully published.
 Power published: CBWWBA (0.002 MW)
MQTT message with mid=28 successfully published.
 Power published: CETHANA (47.47 MW)
MQTT message with mid=29 successfully published.
 Power published: CHALLWF (26.7 MW)
MQTT message with mid=30 successfully published.
 Power published: CHBESS (0.039 MW)MQTT message with mid=31 successfully published.

 Power published: CHYTWF (11.31 MW)
MQTT message with mid=32 successfully published.
 Power published: CLEMGPWF (50.641 MW)
MQTT message with mid=33 successfully published.
 Power published: CLRKCWF (296.108 MW)
MQTT message with mid=34 successfully published.
 Power published: CLUNY (18.064 MW)
MQTT message with mid=35 successfully published.
 Power published: COLWF01 (115.956 MW)
MQTT message with mid=36 successfully published.
 Power published: CONDONG1 (20.88 MW)
MQTT message with mid=37 successfully published.
 Power published: COOPGWF (328.52 MW)
MQTT message with mid=38 successfully published.
 Power published: CROOKWF2 (76.613 MW)MQTT message with mid=39 successfully published.

 Power published: CROOKWF3 (41.543 MW)
MQTT message with mid=40 successfully published.
 Power published: CROWLWF (58.264 MW)
MQTT message with mid=41 successfully published.
 Power published: CRURWF1 (124.897 MW)
MQTT message with mid=42 successfully published.
 Power published: CTHLWF (14.261 MW)MQTT message with mid=43 successfully published.

 Power published: CULLERIN (24.09 MW)
MQTT message with mid=44 successfully published.
 Power published: DALNTH (0.084 MW)MQTT message with mid=45 successfully published.

 Power published: DARTM (109.8 MW)
MQTT message with mid=46 successfully published.
 Power published: DEVILS_G (46.112 MW)
MQTT message with mid=47 successfully published.
 Power published: DIAPURWF (7.3 MW)
MQTT message with mid=48 successfully published.
 Power published: DPNTB (0.049 MW)
MQTT message with mid=49 successfully published.
 Power published: DULAWF (172.8 MW)
MQTT message with mid=50 successfully published.
 Power published: DUNDWF (77.28 MW)MQTT message with mid=51 successfully published.

 Power published: EILDON (47.0 MW)
MQTT message with mid=52 successfully published.
 Power published: ELAINEWF (38.66 MW)MQTT message with mid=53 successfully published.

 Power published: ERARING (463.862 MW)
MQTT message with mid=54 successfully published.
 Power published: ERB (1.086 MW)
MQTT message with mid=55 successfully published.
 Power published: FISHER (44.87 MW)
MQTT message with mid=56 successfully published.
 Power published: FLYCRKWF (8.72 MW)MQTT message with mid=57 successfully published.

 Power published: GANNBESS (0.29 MW)
MQTT message with mid=58 successfully published.
 Power published: GERMCRK (16.488 MW)
MQTT message with mid=59 successfully published.
 Power published: GORDON (24.423 MW)
MQTT message with mid=60 successfully published.
 Power published: GPWFEST (148.88 MW)MQTT message with mid=61 successfully published.

 Power published: GRANWF (31.22 MW)
MQTT message with mid=62 successfully published.
 Power published: GREENB (0.045 MW)
MQTT message with mid=63 successfully published.
 Power published: GSTONE (149.769 MW)
MQTT message with mid=64 successfully published.
 Power published: GSWF (200.66 MW)MQTT message with mid=65 successfully published.

 Power published: GULLRGWF (119.063 MW)
MQTT message with mid=66 successfully published.
 Power published: GUNNING (34.678 MW)
MQTT message with mid=67 successfully published.
 Power published: HALLWF (74.15 MW)
MQTT message with mid=68 successfully published.
 Power published: HALLWF2 (56.52 MW)
MQTT message with mid=69 successfully published.
 Power published: HBESS (0.3 MW)
MQTT message with mid=70 successfully published.
 Power published: HD1WF (45.06 MW)
MQTT message with mid=71 successfully published.
 Power published: HORNSDAL (90.3 MW)
MQTT message with mid=72 successfully published.
 Power published: HORNSDAL2 (96.5 MW)
MQTT message with mid=73 successfully published.
 Power published: HORNSDAL3 (107.6 MW)
MQTT message with mid=74 successfully published.
 Power published: HORNSDPR (8.2 MW)
MQTT message with mid=75 successfully published.
 Power published: HUMENSW (21.028 MW)
MQTT message with mid=76 successfully published.
 Power published: HVWW (0.009 MW)
MQTT message with mid=77 successfully published.
 Power published: JEERB (0.1 MW)
MQTT message with mid=78 successfully published.
 Power published: KABANWF (110.789 MW)
MQTT message with mid=79 successfully published.
 Power published: KAREEYA (21.445 MW)
MQTT message with mid=80 successfully published.
 Power published: KESS1 (2.23 MW)MQTT message with mid=81 successfully published.

 Power published: KIATAWF (29.3 MW)
MQTT message with mid=82 successfully published.
 Power published: KOGANCK (719.94 MW)
MQTT message with mid=83 successfully published.
 Power published: LADBROKE (0.01 MW)
MQTT message with mid=84 successfully published.
 Power published: LBBESS (0.15 MW)MQTT message with mid=85 successfully published.

 Power published: LEM_WIL (86.928 MW)
MQTT message with mid=86 successfully published.
 Power published: LGAPWF1 (49.33 MW)
MQTT message with mid=87 successfully published.
 Power published: LI_WY_CA (154.484 MW)
MQTT message with mid=88 successfully published.
 Power published: LKBONNY1 (41.975 MW)
MQTT message with mid=89 successfully published.
 Power published: LKBONNY3 (16.747 MW)
MQTT message with mid=90 successfully published.
 Power published: LKBONNY_2 (87.009 MW)
MQTT message with mid=91 successfully published.
 Power published: LOYYANGA (415.0 MW)
MQTT message with mid=92 successfully published.
 Power published: LOYYB (451.5 MW)
MQTT message with mid=93 successfully published.
 Power published: LVES (0.5 MW)
MQTT message with mid=94 successfully published.
 Power published: MACARTH (126.2 MW)
MQTT message with mid=95 successfully published.
 Power published: MACKNTSH (51.81 MW)
MQTT message with mid=96 successfully published.
 Power published: MANNUMB (0.18 MW)MQTT message with mid=97 successfully published.

 Power published: MBAHNTH (20.2 MW)
MQTT message with mid=98 successfully published.
 Power published: MCINTYR (139.076 MW)
MQTT message with mid=99 successfully published.
 Power published: MCKAY (0.02 MW)
MQTT message with mid=100 successfully published.
 Power published: MEADOWBK (43.442 MW)
MQTT message with mid=101 successfully published.
 Power published: MEWF (49.5 MW)
MQTT message with mid=102 successfully published.
 Power published: MILLMERN (0.0 MW)
MQTT message with mid=103 successfully published.
 Power published: MINTARO (0.085 MW)
MQTT message with mid=104 successfully published.
 Power published: MLSP (0.013 MW)MQTT message with mid=105 successfully published.

 Power published: MLWF (11.55 MW)
MQTT message with mid=106 successfully published.
 Power published: MOORAWF1 (248.89 MW)
MQTT message with mid=107 successfully published.
 Power published: MP (448.847 MW)
MQTT message with mid=108 successfully published.
 Power published: MRTLSWF (89.57 MW)
MQTT message with mid=109 successfully published.
 Power published: MTGELWF (59.523 MW)
MQTT message with mid=110 successfully published.
 Power published: MTMERCER (78.1 MW)
MQTT message with mid=111 successfully published.
 Power published: MTMILLAR (34.0 MW)
MQTT message with mid=112 successfully published.
 Power published: MUSSELRO (46.0 MW)MQTT message with mid=113 successfully published.

 Power published: MUWAWF (202.65 MW)
MQTT message with mid=114 successfully published.
 Power published: NBHWF (106.2 MW)
MQTT message with mid=115 successfully published.
 Power published: OAKLAND (34.4 MW)
MQTT message with mid=116 successfully published.
 Power published: PALOONA (29.41 MW)
MQTT message with mid=117 successfully published.
 Power published: PAREPW (48.43 MW)
MQTT message with mid=118 successfully published.
 Power published: PIONEER (43.2 MW)
MQTT message with mid=119 successfully published.
 Power published: PORTWF (59.0 MW)
MQTT message with mid=120 successfully published.
 Power published: PTINA (3.31 MW)
MQTT message with mid=121 successfully published.
 Power published: QBYNB (0.176 MW)
MQTT message with mid=122 successfully published.
 Power published: RANGEB (0.05 MW)
MQTT message with mid=123 successfully published.
 Power published: REECE (118.87 MW)
MQTT message with mid=124 successfully published.
 Power published: REPULSE (32.886 MW)
MQTT message with mid=125 successfully published.
 Power published: RESS (0.68 MW)
MQTT message with mid=126 successfully published.
 Power published: RIVNB (0.115 MW)
MQTT message with mid=127 successfully published.
 Power published: ROWALLAN (0.005 MW)
MQTT message with mid=128 successfully published.
 Power published: ROYALLA (0.001 MW)MQTT message with mid=129 successfully published.

 Power published: RPCG (13.8 MW)
MQTT message with mid=130 successfully published.
 Power published: RUBICON (0.585 MW)
MQTT message with mid=131 successfully published.
 Power published: RYANCWF (75.16 MW)
MQTT message with mid=132 successfully published.
 Power published: RYEPARK (202.695 MW)
MQTT message with mid=133 successfully published.
 Power published: SALTCRK (15.35 MW)
MQTT message with mid=134 successfully published.
 Power published: SAPHWF1 (233.248 MW)
MQTT message with mid=135 successfully published.
 Power published: SHOAL (43.47 MW)
MQTT message with mid=136 successfully published.
 Power published: SMTHBES1 (0.046 MW)
MQTT message with mid=137 successfully published.
 Power published: SNOWNTH (126.7 MW)
MQTT message with mid=138 successfully published.
 Power published: SNOWSTH (114.5 MW)
MQTT message with mid=139 successfully published.
 Power published: SNOWTOWN (92.586 MW)
MQTT message with mid=140 successfully published.
 Power published: SNOWY3 (61.8 MW)
MQTT message with mid=141 successfully published.
 Power published: SNOWY6 (52.6 MW)
MQTT message with mid=142 successfully published.
 Power published: STANWELL (245.23 MW)
MQTT message with mid=143 successfully published.
 Power published: STARFHILL (6.698 MW)
MQTT message with mid=144 successfully published.
 Power published: STOCKYD (337.78 MW)
MQTT message with mid=145 successfully published.
 Power published: STWF (136.271 MW)
MQTT message with mid=146 successfully published.
 Power published: SWAN_E (0.58 MW)
MQTT message with mid=147 successfully published.
 Power published: TARALGA (48.698 MW)
MQTT message with mid=148 successfully published.
 Power published: TARONG (0.6 MW)
MQTT message with mid=149 successfully published.
 Power published: TARONGN (278.5 MW)
MQTT message with mid=150 successfully published.
 Power published: TARRALEA (59.7 MW)
MQTT message with mid=151 successfully published.
 Power published: TB2SF (0.347 MW)
MQTT message with mid=152 successfully published.
 Power published: TEMPB (2.0 MW)
MQTT message with mid=153 successfully published.
 Power published: TIB (4.55 MW)
MQTT message with mid=154 successfully published.
 Power published: TORRIS (0.0 MW)
MQTT message with mid=155 successfully published.
 Power published: TULLYSM (9.9 MW)
MQTT message with mid=156 successfully published.
 Power published: TUNGATIN (80.25 MW)
MQTT message with mid=157 successfully published.
 Power published: ULBESS (0.6 MW)
MQTT message with mid=158 successfully published.
 Power published: VP (0.0 MW)
MQTT message with mid=159 successfully published.
 Power published: WALGRV (0.209 MW)
MQTT message with mid=160 successfully published.
 Power published: WAMBOWF (65.23 MW)
MQTT message with mid=161 successfully published.
 Power published: WANDBG (2.246 MW)
MQTT message with mid=162 successfully published.
 Power published: WATERLWF (103.5 MW)
MQTT message with mid=163 successfully published.
 Power published: WAUBRAWF (53.472 MW)
MQTT message with mid=164 successfully published.
 Power published: WDBESS (0.243 MW)
MQTT message with mid=165 successfully published.
 Power published: WDBESS2 (0.254 MW)
MQTT message with mid=166 successfully published.
 Power published: WGWF (106.9 MW)
MQTT message with mid=167 successfully published.
 Power published: WKIEWA (16.0 MW)
MQTT message with mid=168 successfully published.
 Power published: WOODLWN (13.997 MW)
MQTT message with mid=169 successfully published.
 Power published: WOOLNTH1 (25.97 MW)
MQTT message with mid=170 successfully published.
 Power published: WPWF (44.05 MW)
MQTT message with mid=171 successfully published.
 Power published: WRWF1 (36.902 MW)
MQTT message with mid=172 successfully published.
 Power published: YALLOURN (250.75 MW)
MQTT message with mid=173 successfully published.
 Power published: YAMBUK (4.9 MW)
MQTT message with mid=174 successfully published.
 Power published: YARWUN (85.01 MW)
MQTT message with mid=175 successfully published.
 Power published: YENDONWF (94.95 MW)
MQTT message with mid=176 successfully published.
 Power published: YSWF (20.2 MW)MQTT message with mid=177 successfully published.

Finished timestamp 2025-10-01 00:00:00+10:00. Waiting 0s before next batch...

Publishing data for timestamp: 2025-10-01 00:05:00+10:00
 Power published: ADP (0.046 MW)
MQTT message with mid=178 successfully published.
 Power published: ANGASTON (0.1 MW)
MQTT message with mid=179 successfully published.
 Power published: ARWF (33.3 MW)
MQTT message with mid=180 successfully published.
 Power published: B2PS (0.081 MW)
MQTT message with mid=181 successfully published.
 Power published: BANGOWF (95.399 MW)
MQTT message with mid=182 successfully published.
 Power published: BASTYAN (62.41 MW)
MQTT message with mid=183 successfully published.
 Power published: BAYSW (555.807 MW)
MQTT message with mid=184 successfully published.
 Power published: BBATTERY (0.368 MW)
MQTT message with mid=185 successfully published.
 Power published: BHB (2.178 MW)
MQTT message with mid=186 successfully published.
 Power published: BHWF (4.476 MW)MQTT message with mid=187 successfully published.

 Power published: BIALAWF (70.098 MW)
MQTT message with mid=188 successfully published.
 Power published: BLUEGSF (0.101 MW)
MQTT message with mid=189 successfully published.
 Power published: BLUFF (46.5 MW)
MQTT message with mid=190 successfully published.
 Power published: BLYTHB (0.11 MW)
MQTT message with mid=191 successfully published.
 Power published: BOCOROCK (53.98 MW)
MQTT message with mid=192 successfully published.
 Power published: BODWF (44.137 MW)
MQTT message with mid=193 successfully published.
 Power published: BOLIVAR (0.003 MW)
MQTT message with mid=194 successfully published.
 Power published: BRNDBES (0.137 MW)
MQTT message with mid=195 successfully published.
 Power published: BRYB1WF1 (129.149 MW)
MQTT message with mid=196 successfully published.
 Power published: BULGANA (47.56 MW)
MQTT message with mid=197 successfully published.
 Power published: BUTLERSG (6.5 MW)
MQTT message with mid=198 successfully published.
 Power published: BWTR1 (23.836 MW)
MQTT message with mid=199 successfully published.
 Power published: CALLIDEC1 (0.0 MW)
MQTT message with mid=200 successfully published.
 Power published: CALL_B (279.2 MW)MQTT message with mid=201 successfully published.

 Power published: CANUNDA1 (34.74 MW)
MQTT message with mid=202 successfully published.
 Power published: CAPBES (0.94 MW)
MQTT message with mid=203 successfully published.
 Power published: CAPTL_WF (115.014 MW)
MQTT message with mid=204 successfully published.
 Power published: CATHROCK (38.7 MW)
MQTT message with mid=205 successfully published.
 Power published: CBWWBA (0.016 MW)
MQTT message with mid=206 successfully published.
 Power published: CETHANA (44.477 MW)
MQTT message with mid=207 successfully published.
 Power published: CHALLWF (26.7 MW)
MQTT message with mid=208 successfully published.
 Power published: CHBESS (0.213 MW)
MQTT message with mid=209 successfully published.
 Power published: CHYTWF (13.33 MW)
MQTT message with mid=210 successfully published.
 Power published: CLEMGPWF (52.802 MW)
MQTT message with mid=211 successfully published.
 Power published: CLRKCWF (288.522 MW)
MQTT message with mid=212 successfully published.
 Power published: CLUNY (18.069 MW)
MQTT message with mid=213 successfully published.
 Power published: COLWF01 (115.151 MW)
MQTT message with mid=214 successfully published.
 Power published: CONDONG1 (20.91 MW)
MQTT message with mid=215 successfully published.
 Power published: COOPGWF (328.94 MW)
MQTT message with mid=216 successfully published.
 Power published: CROOKWF2 (75.733 MW)
MQTT message with mid=217 successfully published.
 Power published: CROOKWF3 (36.667 MW)
MQTT message with mid=218 successfully published.
 Power published: CROWLWF (60.477 MW)
MQTT message with mid=219 successfully published.
 Power published: CRURWF1 (126.397 MW)
MQTT message with mid=220 successfully published.
 Power published: CTHLWF (14.652 MW)
MQTT message with mid=221 successfully published.
 Power published: CULLERIN (24.86 MW)
MQTT message with mid=222 successfully published.
 Power published: DALNTH (0.099 MW)
MQTT message with mid=223 successfully published.
 Power published: DARTM (109.8 MW)
MQTT message with mid=224 successfully published.
 Power published: DEVILS_G (34.986 MW)
MQTT message with mid=225 successfully published.
 Power published: DIAPURWF (7.3 MW)
MQTT message with mid=226 successfully published.
 Power published: DPNTB (0.298 MW)MQTT message with mid=227 successfully published.

 Power published: DULAWF (172.9 MW)
MQTT message with mid=228 successfully published.
 Power published: DUNDWF (66.35 MW)MQTT message with mid=229 successfully published.

 Power published: EILDON (47.04 MW)
MQTT message with mid=230 successfully published.